# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-25 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0051_journal_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSRN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srn', models.CharField(help_text='Library of Congress SRN.', max_length=12)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
            ],
        ),
    ]
